<?xml version="1.0" encoding="utf-8"?>
<Project>

    <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props" />

    <PropertyGroup>
        <ArtifactsPath>$(SolutionDirectory).artifacts/examples</ArtifactsPath>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <IsPackable>false</IsPackable>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

</Project>
