<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>MonoGame backend integration and rendering support for TGui.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TGui\TGui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>